import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

import Image from 'next/image';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata =
{
  title:'Next.js',
  description:'Generated by Next.js',
}
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">

        {/* <body>
          {children}</body> */}
          <body className="bg-blue-100 text-green-900">
           
        <header className="bg-blue-700 text-red shadow-md">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between px-4 py-3 space-y-10 md:space-y-5">
            
            {/* Logo */}
            <div className="text-2xl font-bold">
              <Link href=" /">  </Link>
          
              <Image
        src="/b.png"
        width={50}
        height={50}
        className="hidden md:block"
        alt="Screenshots of the dashboard project showing desktop version"
      />
            </div>

            {/* Navigation Menu */}
            <nav className="flex space-x-4 text-base font-medium">
              <Link href="/" className="hover:underline">Home</Link>
              <Link href="/blog">Blog</Link>
              <Link href="/products" className="hover:underline">Products</Link>
              <Link href="/docs" className="hover:underline">Documents</Link>
              <Link href="/Prediction" className="hover:underline">Prediction</Link>
            </nav>

            {/* Search Bar */}
            <form className="flex w-full md:w-auto items-center space-x-2">
              <input
                type="text"
                placeholder="Search here..."
                className="w-full md:w-40 px-3 py-1 rounded-md text-black focus:outline-none"
              />
              <button
                type="submit"
                className="bg-yellow-400 hover:bg-yellow-500 text-black px-4 py-1 rounded-md font-semibold"
              >
                Search
              </button>
            </form>
          </div>
        </header>

        <main className="max-w-7xl mx-auto py-10 px-4">
        
          {children}</main>
      </body>
      </html>
    )
  }
  